spring :
  mail :
    host : smtp.gmail.com
    port : 587
    username : 'minjae29525866@gmail.com'
    password : 'ggqfdlmpzanholpj'
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true
            required : true