spring:
  profiles:
    active: mail
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/finalproject?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: testuser
    password: 5678
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
custom:
  rebate:
    wholesalePriceRate: 0.5
  order:
    cancelAvailableMinutes: 60
  site:
    name: M-BOOKS
    baseUrl: "http://localhost:8080"